apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: troz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: troz
    app.kubernetes.io/part-of: byoc-app-zlxo
  name: troz
spec:
  rules:
  - host: troz-byoc-xplp-tenant.apps.c7623f48c5a832b3483d.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: troz
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
